---
locale: es
tags: []
layout: input_bottom
editor: 0
type: interactive
extra_visible: true
teacher_info: ''
manual_evaluation: false
progressive_expectations: false
choices: []
goal:
  kind: queries_match
  regexps:
  - ^es_peripatetica\s*\(\s*\"atletismo\"\s*\,\s*\"Argentina\"\s*\,\s*10\s*\)\s*$
  - ^es_peripatetica\s*\(\s*\"filosofía\"\s*\,\s*\"Argentina\"\s*\,\s*3\s*\)\s*$
  - ^es_peripatetica\s*\(\s*\"ingeniería\"\s*\,\s*\"Canadá\"\s*\,\s*1\s*\)\s*$
  - ^es_peripatetica\s*\(\s*\"filosofía\"\s*\,\s*\"Grecia\"\s*\,\s*5\s*\)\s*$
name: La verdad detrás de la conjunción
