---
locale: es
tags: []
layout: input_bottom
editor: 0
type: interactive
extra_visible: false
teacher_info: ''
manual_evaluation: false
progressive_expectations: false
choices: []
goal:
  kind: queries_match
  regexps:
  - "^gano\\s*\\(\\s*True\\s*\\,\\s*25\\s*\\)\\s*"
  - "^gano\\s*\\(\\s*False\\s*\\,\\s*30\\s*\\)\\s*"
  - "^gano\\s*\\(\\s*False\\s*\\,\\s*20\\s*\\)\\s*"
  - "^gano\\s*\\(\\s*True\\s*\\,\\s*31\\s*\\)\\s*"
name: "¡Juguemos al T.E.G.!"
